version: 2
jobs:
  build_test_extension_firefox:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          command: |
            cd frontend/
            sudo npm install --global web-ext
            web-ext lint
            web-ext build
      - store_artifacts:
          path: ~/project/frontend/web-ext-artifacts/hatespeech-1.0.zip
  test_backend:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
      - run:
          command: |
            cd hatespeech_backend/
            sudo pip install -r requirements.txt
            pytest
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: ~/project/hatespeech_backend/htmlcov

workflows:
  version: 2
  build:
    jobs:
      - build_test_extension_firefox
      - test_backend
