version: 2
jobs:
  build:
    working_directory: ~/plugin
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
  test:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
