version: 2
jobs:
  build:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
  test:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
      - run:
          command: |
            cd hatespeech_backend/
            sudo pip install -r requirements.txt
            pytest
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: ~/project/hatespeech_backend/htmlcov
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
