version: 2
jobs:
  build:
    working_directory: ~/plugin
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
  test:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          command: |
            cd hatespeech_backend/
            pip install requirements.txt
            python -m pytest -s tests/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
